### ISSUE TITLE
Exception during login

### ISSUE THREAD

**Issue by rmaspoch** [auth0-samples/auth0-aspnetcore-sample#1]
I'm following along the AspNet Core quickstart and I get the following exception while trying to login:

_SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: RTM1NzUzMkJCMDIwRjc5MTQ4MTIyNzU2QTQ4OUI0QkZCOTYxMjIyRg
Microsoft.IdentityModel.Tokens.RsaSecurityKey , KeyId: RTM1NzUzMkJCMDIwRjc5MTQ4MTIyNzU2QTQ4OUI0QkZCOTYxMjIyRg
'.
Exceptions caught:
'System.ArgumentException: IDX10634: Unable to create the SignatureProvider.

SignatureAlgorithm: 'HS256', SecurityKey: 'Microsoft.IdentityModel.Tokens.X509SecurityKey'
is not supported._

Any help will be greatly appreciated.

Thanks,
Rudy

**Comment by webbkvalite** [comment]
If you're using a HS256-key, it can be fixed by setting the TokenValidationParameters on the OpenIdConnectOptions.
First turn the clientSecret into a byte[] like so:
            var keyAsBase64 = Configuration["auth0:clientSecret"].Replace('_', '/').Replace('-', '+');
            var keyAsBytes = Convert.FromBase64String(keyAsBase64);
Next add the TokenValidationParameters like so:
TokenValidationParameters =
                {
                    IssuerSigningKey = new SymmetricSecurityKey(keyAsBytes)
                }

**Comment by esmondmissen** [comment]
I'm having the same issue with this one. I've just followed the basic login tutorial for .net core. Where am I able to set the TokenValidationParameters? I can't seem to find a reference to it following the tutorial.

**Comment by hjgraca** [comment]
If you are getting this error it means you haven't changed the settings in the Auth0 dashboard. You need to change `JsonWebToken Signature Algorithm` to use `RS256` under advanced options of your client.

**Comment by alatchi** [comment]
Thank you very much.
This fix the error.
I've changed from HmacSha256Signature to RsacSha256Signature.
