### ISSUE TITLE
I don't have a name claim in .net core User Profile code.

### ISSUE THREAD

**Issue by aniltan** [auth0-samples/auth0-aspnetcore-sample#12]
I've been following the sample for .net core, but in User Profile step, I don't have name in the claim, so I can't show it on the UI. Am I missing anything?

**Comment by jerriep** [comment]
What scopes are you requesting? You need to either add the `profile` scope (in which case you will get the entire profile), or be more specific and add just the `name` scope.

Please see these lines:
https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/master/05-User-Profile/SampleMvcApp/Startup.cs#L155-L159

**Comment by jerriep** [comment]
@aniltan I am closing this issue, since setting the correct `scope` should sort you out. If you still have an issue, please let me know.
