### ISSUE TITLE
Problem with Logout in sample 01-Login in VS2017 branch

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-aspnetcore-sample#16]
Running the sample with Visual Studio 2017 RC, click on Logout results with:

![image](https://cloud.githubusercontent.com/assets/2712405/23517730/2e370a8c-ff3f-11e6-9321-2ef45b9dc575.png)

The details on this problem are:
```
The "returnTo" querystring parameter "http://localhost:8000/" is not defined as a valid URL in "Allowed Logout URLs". Valid values ares: [http://localhost:8000/signout-auth0]. To add a new URL, please do it here: https://manage.auth0.com/#/applications/kiiH4xCOeCmzFulls4Nv04WdknSMv7VO/settings
```

This claim is not correct - here is my relevant settings screenshot:

![image](https://cloud.githubusercontent.com/assets/2712405/23517846/9410c2a8-ff3f-11e6-94fc-7ec6860415d8.png)

I traced through the **[this code](https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/vs2017/01-Login/SampleMvcApp/Startup.cs#L96-L120)** which seems new in this version. The error message shown above takes place executing **[this line](https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/vs2017/01-Login/SampleMvcApp/Startup.cs#L115)**

I am attaching several trace log files with time stamp matching the above run:

[tracelogs.zip](https://github.com/auth0-samples/auth0-aspnetcore-sample/files/814552/tracelogs.zip)

**Comment by adriatic** [comment]
This same sample works fine if I replace the current async handling of the logout even with the code that is still used in the original text on the **[quick start](https://manage.auth0.com/#/clients/kiiH4xCOeCmzFulls4Nv04WdknSMv7VO/quickstart)** page.

**Comment by jerriep** [comment]
You need to add the URL which your are passing in the `RedirectUri` to the **Allowed Logout URLs** textbox of your Client in the Auth0 Dashboard.

Thank you for pointing this out. I will update the quickstarts appropriately

**Comment by adriatic** [comment]
Is there a clear benefit of using this async version **`public async Task Logout()`** (which requires the **[event processing code](https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/vs2017/01-Login/SampleMvcApp/Startup.cs#L96-L120)**), when compared with just 

```
        public IActionResult Logout()
        {
            HttpContext.Authentication.SignOutAsync("Auth0");
            HttpContext.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Home");
        }
```

**Comment by adriatic** [comment]
Verified [your explanation above](https://github.com/auth0-samples/auth0-aspnetcore-sample/issues/16#issuecomment-283806303) - of course that this was the problem 😏

**Comment by jerriep** [comment]
Hmmm, I am not sure whether there is a clear benefit. The way it is currently set up, Auth0 will redirect to whichever URL after the user has signed out. That requires a bit more work with the event handler code.

It is also however acceptable (I believe) to just let the application redirect - as was the case with the initial code.

**Comment by jerriep** [comment]
@adriatic Actually Nico just reminded me that in the way the code was before (i.e. the way it is currently in the quickstarts), the user was never logged actually out of Auth0 at all. 

So the new way of doing it is definitely the correct way.

**Comment by adriatic** [comment]
Interesting observation (it would really worry me to find that out in my app).

I am using the async logout now and it works fine.
