### ISSUE TITLE
VS 2017 versions of this sample collection

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-aspnetcore-sample#17]
It seems that only the 01-Login sample was converted, so I would much prefer to not race with Jerrie who will to the others first and wait until Jerrie declares them done.

Since time is of issue to me and I really care about `user profiles`, `rules` and `authorization`, I might be forced to try to convert them myself if Jerrie's schedule is beyond my time limit :-)

**Comment by jerriep** [comment]
Vs2017 samples will be done after VS2017 is released - which is next week.

**Comment by adriatic** [comment]
Good. I am currently trying all samples using the already converted 01-Login as the "template", so I can verify the use of Auth0 in my app

**Comment by adriatic** [comment]
@jerriep assuming that this data will help in getting this new code running:

Adding the **[Auth0 Setting object](https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/vs2017/01-Login/SampleMvcApp/Startup.cs#L44)** line fails with error message shown below

![image](https://cloud.githubusercontent.com/assets/2712405/23640034/f17e262a-02b8-11e7-8fc6-f4bb84f4e8fa.png)

This used to work very recently (three days ago) when I upgraded my dotnet core modules to be:

```
 <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.1" />
  </ItemGroup>
```

If there is an obvious fix for this, I would appreciate your advice, Jerrie.

**Comment by jerriep** [comment]
@adriatic Can you please check out the VS2017 branch:
https://github.com/auth0-samples/auth0-aspnetcore-sample/tree/vs2017

It contains full working copies of all the quickstart samples converted to VS2017. I tested this and all of them worked.

**Comment by adriatic** [comment]
@jerriep - the code I just pointed to is from the VS2017 branch (I would not make such rookie's mistake to bug you with trivialities) - see https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/vs2017/01-Login/SampleMvcApp/Startup.cs#L44

The only way we could both be right is that your **[SampleMvcApp.csproj](https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/vs2017/01-Login/SampleMvcApp/SampleMvcApp.csproj)** is already behind current (the version that is most likely be released as RTM tomorrow) **and** that the 
**`Microsoft.Extensions.Configuration" Version="1.1.1" `** treats the line

```
services.Configure<Auth0Settings>(Configuration.GetSection("Auth0"));
```

(please consider that I deserve more credit than what you were ready to give me 😄 )

**Comment by jerriep** [comment]
@adriatic Thank you. I will leave this for now. After VS2017 is finally released tomorrow I will do a check once again to ensure everything. At this point we are working with pre-release software, so inconsistencies can creep in.

Also, I will be traveling this week, which means I will most likely only be able to ensure all is working at the beginning of this week.

Apologies for the inconvenience with this.

**Comment by adriatic** [comment]
No inconvenience at all - as I would rather use the most recent dotnet core than to downgrade my app to the version numbers that work for you. I really appreciate your readiness to help - thank you!!

This article might be of some help as well http://www.strathweb.com/2016/09/strongly-typed-configuration-in-asp-net-core-without-ioptionst/

It's almost midnight here, so I will look into that tomorrow. If it is of common interest, I will add more data here.

**Comment by jerriep** [comment]
@adriatic I do not know what to tell you about this error.

I updated the **01-Login** project to all the latest NuGet packages just now (including `Microsoft.Extensions.Configuration" Version="1.1.1"`) and I do not get the error you are getting.

When you get errors like these, please share your project with us, as it is impossible for us to try and track down the issue from screenshots alone.

That being said, I would appreciate, if possible, it you can wait until after VS2017 is released as right now we are working with a moving target.

**Comment by adriatic** [comment]
I believe that this issue can be closed as the current set of samples that are written for Visual Studio usage work fine with VS 2017 (at least the dotnet core subset)
