### ISSUE TITLE
Parallels and differences between two sample sets

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-aspnetcore-sample#19]
I am looking at [auth0-aspnetcore-sample](https://github.com/auth0-samples/auth0-aspnetcore-sample) and [auth0-aspnetcore-webapi-sample](https://github.com/auth0-samples/auth0-aspnetcore-webapi-sample) and trying to figure the reason that both of them exists. 

Being **very familiar** with the first set ([auth0-aspnetcore-sample](https://github.com/auth0-samples/auth0-aspnetcore-sample)) and not at all familiar with the second (I plan to have a look at that tomorrow), I can only guess that the first set deals with the single aspnet core application and authorization issues , while the second shows the back-and application acting as an API server. 

If this is correct, then my immediate reaction is that the reader is expected to use a tool like postman in order to verify the authentication and authorization issues.

Now, if this second guess is correct, then I would suggest to further enhance this tutorial as it is to a large extent a function of its client (SPA, other server, etc). 

Probably the best approach to address this would be to create a higher level document that explains the use cases for all of the samples in the collection at https://github.com/auth0-samples.

**Comment by jerriep** [comment]
@adriatic Yes, you figured it out :)

https://github.com/auth0-samples/auth0-aspnetcore-sample is for a normal ASP.NET MVC application, and shows how to add authentication to your app.

https://github.com/auth0-samples/auth0-aspnetcore-webapi-sample shows how to add authentication with JSON Web Tokens to an API.

Both these samples are not really meant to be explanatory by themselves. They are instead the source code for the Web App and Web API quickstarts respectively (as is explained in their README files:

* https://auth0.com/docs/quickstart/webapp/aspnet-core
* https://auth0.com/docs/quickstart/backend/aspnet-core-webapi

Going through those quickstarts will walk you through the process from end-to-end. The API quickstart also shows how to test the API from Postman.

**However:** As you noted these quickstarts are standalone. So for example, if you use the ASP.NET Core API quickstart, you will need to pair it with a SPA or Native App which will call the actual API. You can follow the quickstarts for SPA/Native App of choice in order to do that

**Comment by adriatic** [comment]
My intent (then getting your confirmation about my guesses) was to suggest a significant improvement over the existing tutorials - as you have a good writing talent paralleled with good understanding of the subject you are describing. So, I will restate my sentence from [above](https://github.com/auth0-samples/auth0-aspnetcore-sample/issues/19#issue-215606649):

> Probably the best approach to address this would be to create a higher level document that explains the use cases for all of the samples in the collection at https://github.com/auth0-samples.

Note that "you" in this context is the collective Auth0 you - as Auth0 PaaS is really only as good as it weakest documents. Being a big fan of Auth0 (and a friend with the two of its founders) my comments are totally unselfish with the point that I would consider helping this effort in the right circumstances.

Example: I am working (with my team) on a "full stack" app with Aurelia front end and aspnet core web api on the back end, as an SSO project for Aurelia community. As I am having a heck of a problem trying to match the Auth0 Aurelia quick start with the samples that you wrote, I would be happy to contribute the whole app to your collection after its done - with world class documentation of course.

**Comment by adriatic** [comment]
Also a comment on

> Both these samples are not really meant to be explanatory by themselves. They are instead the source code for the Web App and Web API quickstarts respectively (as is explained in their README files:
 - https://auth0.com/docs/quickstart/webapp/aspnet-core
 - https://auth0.com/docs/quickstart/backend/aspnet-core-webapi
> Going through those quickstarts will walk you through the process from end-to-end. The API quickstart also shows how to test the API from Postman.

I am indeed aware of this - my point was to indicate a need for some global (relative to all sample collection) document that states what you just explained to me, probably with more meat on the bones

**Comment by jerriep** [comment]
The fact that there are no "full stack" samples is a problem. AFAIK we are looking into providing end-to-end samples at some point, so everyone is aware of this shortcoming.

As you, I am personally also frustrated with this, and have planned some personal open source side projects which will hopefully assist others in understanding how to put a full application together from end to end. 

If you want to make a source sample available which other customers can look at, that would be awesome!

As for the use-cases for all the samples - yes that is a good idea, and also something which I personally looked at in the past. I will mention this again internally and see whether we can get some - preferably searchable - index to all samples set up.

**Comment by adriatic** [comment]
> As you, I am personally also frustrated with this, and have planned some personal open source side projects which will hopefully assist others in understanding how to put a full application together from end to end.

Consider joining our team in the [carmel](https://github.com/aurelia-ui-toolkits/carmel) project which is a perfect opportunity for both of us. Note that we have a "special relationship" with Auth0 that gave us a free OSS license and our goal is to introduce Auth0 as the preferred provider to the whole community.

**Comment by jerriep** [comment]
Just a quick further note on the end-to-end samples: You also need to understand that every customer's need are different, so it will be difficult to provide samples that everyone can use. In your case for example you would probably like to see a full sample with Aurelia as the SPA, but in reality Aurelia is not much used. So if we do put end-to-end samples together it likely will be for a more "popular" framework such as Angular / React

Our Architecture Scenarios (https://auth0.com/docs/architecture-scenarios) also have 2 end-to-end samples already:

* https://auth0.com/docs/architecture-scenarios/application/web-app-sso
* https://auth0.com/docs/architecture-scenarios/application/server-api

None for SPA / Native clients yet though :(

**Comment by jerriep** [comment]
Thanks for the offer of joining your project, but I have already started on some of my own projects for things which I actually require (see http://www.jerriepelser.com/blog/new-project-geotoast/), so I have no capacity to join other projects at this stage. Feel free to ping me when you have questions however.

**Comment by adriatic** [comment]
Please reconsider your decision to use Vue and use Aurelia. You will be glad!

**Comment by adriatic** [comment]
@jerriep 
> Feel free to ping me when you have questions however.

I really appreciate this 😄
