### ISSUE TITLE
Clarify when UseOpenIdConnectAuthentication is required

### ISSUE THREAD

**Issue by wags** [auth0-samples/auth0-aspnetcore-sample#5]
Hi,

The app I'm working on is most similar to the `03-Login-Custom` example in this repo. I am using only my company's Active Directory (via the Auth0 AD Connector) for authentication, no social logins or anything.

Looking at `Startup.cs`, I'm not sure if I need the following code:

In `Configure`:

``` C#
var options = new OpenIdConnectOptions("Auth0")
{
    ...
};
options.Scope.Clear();
options.Scope.Add("openid");
options.Scope.Add("name");
options.Scope.Add("email");
app.UseOpenIdConnectAuthentication(options);
```

(I am still using the cookie middleware.)

I am trying to streamline the auth for clarity, and also to help figure out why sometimes the `name` claim is populated with the user's email address instead of their full name. I'm starting to think that one is a different issue altogether.

Anyway, is that OIDC code only included to demonstrate the Google login functionality? Am I missing out on a "better" security model by using the Auth0 Authentication API and not saving the JWT?

**Comment by wags** [comment]
I noticed that omitting the OIDC middleware seems to cause other issues. For example, login times are very slow and sometimes time out. Everything performs more reliably when using both the OIDC and cookie middleware.

**Comment by nicosabena** [comment]
The OIDC middleware is used by the application to interact with Auth0 (request an authentication, get the user profile, etc), regardless of what connections you enable on Auth0's side for that particular application.
Your app sees a single OIDC provider (Auth0), which in turns act as a broker to other identity providers, with possibly different protocols (like OAuth, LDAP, SAMLP).
