### ISSUE TITLE
services.Configure<Auth0Settings> error: Add reference to Microsoft.Extensions.Options.ConfigurationExtensions

### ISSUE THREAD

**Issue by sethlivingston** [auth0-samples/auth0-aspnetcore-sample#9]
Per https://github.com/aspnet/Announcements/issues/180.

Adding this to project.json resolves the error on this line in Startup.cs:

    services.Configure<Auth0Settings>(Configuration.GetSection("Auth0"));

**Comment by jerriep** [comment]
Closed in 83ae5c8b117da5113cdbf7af4cdd522bf5b3448b
